# Generated by Django 4.2.27 on 2025-12-16 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0002_alter_vehicleimage_options_vehicleimage_is_primary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, help_text='Previous price', max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, help_text='New price after change', max_digits=10)),
                ('price_difference', models.DecimalField(decimal_places=2, help_text='Difference (new_price - old_price, negative = drop)', max_digits=10)),
                ('percentage_change', models.DecimalField(decimal_places=2, help_text='Percentage change ((new-old)/old * 100)', max_digits=5)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notified_users', models.ManyToManyField(blank=True, help_text='Users who have been notified about this price change', related_name='price_drop_notifications', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['vehicle', '-changed_at'], name='price_alert_vehicle_8f9f95_idx'), models.Index(fields=['-changed_at'], name='price_alert_changed_8b4c1b_idx')],
            },
        ),
    ]
