# Generated by Django 4.2.27 on 2025-12-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="etransfer_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address registered for Interac e-Transfer",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="etransfer_reference_number",
            field=models.CharField(
                blank=True,
                help_text="Interac reference number for completed transfer",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="etransfer_security_answer",
            field=models.CharField(
                blank=True,
                help_text="Security answer (stored securely)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="etransfer_security_question",
            field=models.CharField(
                blank=True, help_text="Security question for e-Transfer", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="type",
            field=models.CharField(
                choices=[
                    ("card", "Credit/Debit Card"),
                    ("bank_account", "Bank Account"),
                    ("mobile_money", "Mobile Money"),
                    ("crypto", "Cryptocurrency"),
                    ("cash", "Cash"),
                    ("interac_etransfer", "Interac e-Transfer"),
                ],
                max_length=20,
            ),
        ),
    ]
