# Generated by Django 4.2.27 on 2025-12-16 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0003_vehicle_drivetrain_vehicle_engine_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleHistoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_status', models.CharField(choices=[('clean', 'Clean Title'), ('salvage', 'Salvage'), ('rebuilt', 'Rebuilt'), ('flood', 'Flood Damage'), ('hail', 'Hail Damage'), ('lemon', 'Lemon Law Buyback'), ('junk', 'Junk')], default='clean', max_length=20, verbose_name='Title Status')),
                ('title_issue_date', models.DateField(blank=True, null=True, verbose_name='Title Issue Date')),
                ('title_state', models.CharField(blank=True, max_length=50, verbose_name='Title State/Province')),
                ('accident_severity', models.CharField(choices=[('none', 'No Accidents'), ('minor', 'Minor Damage'), ('moderate', 'Moderate Damage'), ('severe', 'Severe Damage'), ('total_loss', 'Total Loss')], default='none', max_length=20, verbose_name='Accident Severity')),
                ('total_accidents', models.PositiveIntegerField(default=0, verbose_name='Total Accidents')),
                ('last_accident_date', models.DateField(blank=True, null=True, verbose_name='Last Accident Date')),
                ('total_owners', models.PositiveIntegerField(default=1, verbose_name='Total Owners')),
                ('personal_use', models.BooleanField(default=True, verbose_name='Personal Use')),
                ('rental_use', models.BooleanField(default=False, verbose_name='Rental/Fleet Use')),
                ('taxi_use', models.BooleanField(default=False, verbose_name='Taxi/Rideshare Use')),
                ('police_use', models.BooleanField(default=False, verbose_name='Police/Government Use')),
                ('odometer_rollback', models.BooleanField(default=False, verbose_name='Odometer Rollback Detected')),
                ('odometer_verified', models.BooleanField(default=True, verbose_name='Odometer Verified')),
                ('last_odometer_reading', models.PositiveIntegerField(blank=True, null=True, verbose_name='Last Reading')),
                ('last_odometer_date', models.DateField(blank=True, null=True, verbose_name='Last Reading Date')),
                ('total_service_records', models.PositiveIntegerField(default=0, verbose_name='Total Service Records')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Last Service Date')),
                ('recalls_outstanding', models.PositiveIntegerField(default=0, verbose_name='Outstanding Recalls')),
                ('structural_damage', models.BooleanField(default=False, verbose_name='Structural Damage')),
                ('frame_damage', models.BooleanField(default=False, verbose_name='Frame Damage')),
                ('airbag_deployment', models.BooleanField(default=False, verbose_name='Airbag Deployment')),
                ('report_generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Report Generated')),
                ('report_updated_at', models.DateTimeField(auto_now=True, verbose_name='Report Updated')),
                ('report_source', models.CharField(default='manual', help_text='Source of the report: manual, carfax, autocheck, etc.', max_length=50, verbose_name='Report Source')),
                ('report_confidence', models.CharField(choices=[('high', 'High Confidence'), ('medium', 'Medium Confidence'), ('low', 'Low Confidence')], default='high', max_length=20, verbose_name='Report Confidence')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_report', to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle History Report',
                'verbose_name_plural': 'Vehicle History Reports',
                'ordering': ['-report_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Service Date')),
                ('service_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('brake_service', 'Brake Service'), ('transmission_service', 'Transmission Service'), ('engine_repair', 'Engine Repair'), ('inspection', 'Inspection'), ('recall', 'Recall Repair'), ('other', 'Other')], max_length=50, verbose_name='Service Type')),
                ('odometer_reading', models.PositiveIntegerField(verbose_name='Odometer at Service')),
                ('service_facility', models.CharField(blank=True, max_length=200, verbose_name='Service Facility')),
                ('service_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Cost')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('history_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='vehicle_history.vehiclehistoryreport', verbose_name='History Report')),
            ],
            options={
                'verbose_name': 'Service Record',
                'verbose_name_plural': 'Service Records',
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_number', models.PositiveIntegerField(verbose_name='Owner Number')),
                ('ownership_start', models.DateField(verbose_name='Ownership Start')),
                ('ownership_end', models.DateField(blank=True, null=True, verbose_name='Ownership End')),
                ('state_province', models.CharField(blank=True, max_length=50, verbose_name='State/Province')),
                ('ownership_type', models.CharField(choices=[('personal', 'Personal'), ('lease', 'Lease'), ('rental', 'Rental/Fleet'), ('commercial', 'Commercial'), ('government', 'Government')], default='personal', max_length=50, verbose_name='Ownership Type')),
                ('estimated_annual_miles', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated Annual Miles/KM')),
                ('history_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_records', to='vehicle_history.vehiclehistoryreport', verbose_name='History Report')),
            ],
            options={
                'verbose_name': 'Ownership Record',
                'verbose_name_plural': 'Ownership Records',
                'ordering': ['owner_number'],
            },
        ),
        migrations.CreateModel(
            name='AccidentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_date', models.DateField(verbose_name='Accident Date')),
                ('damage_severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20, verbose_name='Damage Severity')),
                ('front_damage', models.BooleanField(default=False, verbose_name='Front Damage')),
                ('rear_damage', models.BooleanField(default=False, verbose_name='Rear Damage')),
                ('left_side_damage', models.BooleanField(default=False, verbose_name='Left Side Damage')),
                ('right_side_damage', models.BooleanField(default=False, verbose_name='Right Side Damage')),
                ('roof_damage', models.BooleanField(default=False, verbose_name='Roof Damage')),
                ('undercarriage_damage', models.BooleanField(default=False, verbose_name='Undercarriage Damage')),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Repair Cost')),
                ('repair_facility', models.CharField(blank=True, max_length=200, verbose_name='Repair Facility')),
                ('repair_completed', models.BooleanField(default=True, verbose_name='Repair Completed')),
                ('insurance_claim', models.BooleanField(default=False, verbose_name='Insurance Claim Filed')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('history_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accident_records', to='vehicle_history.vehiclehistoryreport', verbose_name='History Report')),
            ],
            options={
                'verbose_name': 'Accident Record',
                'verbose_name_plural': 'Accident Records',
                'ordering': ['-accident_date'],
            },
        ),
        migrations.AddIndex(
            model_name='vehiclehistoryreport',
            index=models.Index(fields=['vehicle'], name='vehicle_his_vehicle_2ebc32_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclehistoryreport',
            index=models.Index(fields=['title_status'], name='vehicle_his_title_s_89fdd7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclehistoryreport',
            index=models.Index(fields=['accident_severity'], name='vehicle_his_acciden_4db356_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerecord',
            index=models.Index(fields=['history_report', 'service_date'], name='vehicle_his_history_7576f3_idx'),
        ),
        migrations.AddIndex(
            model_name='ownershiprecord',
            index=models.Index(fields=['history_report', 'owner_number'], name='vehicle_his_history_539456_idx'),
        ),
        migrations.AddIndex(
            model_name='accidentrecord',
            index=models.Index(fields=['history_report', 'accident_date'], name='vehicle_his_history_3734b5_idx'),
        ),
    ]
