# Generated by Django 6.0 on 2025-12-15 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_docs', 'Pending Documentation'), ('docs_verified', 'Documents Verified'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('ready_to_ship', 'Ready to Ship'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_docs', max_length=20, verbose_name='Status')),
                ('agreed_price_cad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Agreed Price (CAD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('broker', models.ForeignKey(blank=True, limit_choices_to={'role': 'broker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_as_broker', to=settings.AUTH_USER_MODEL, verbose_name='Broker')),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='deals_as_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('dealer', models.ForeignKey(limit_choices_to={'role': 'dealer'}, on_delete=django.db.models.deletion.CASCADE, related_name='deals_as_dealer', to=settings.AUTH_USER_MODEL, verbose_name='Dealer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('title', 'Vehicle Title'), ('id', 'Buyer ID'), ('payment_proof', 'Payment Proof'), ('export_permit', 'Export Permit'), ('customs', 'Customs Declaration'), ('other', 'Other')], max_length=20, verbose_name='Document Type')),
                ('file', models.FileField(upload_to='documents/', verbose_name='File')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='deals.deal', verbose_name='Deal')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('negotiating', 'Negotiating'), ('converted', 'Converted to Deal'), ('lost', 'Lost')], default='new', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('broker', 'Broker'), ('direct', 'Direct Contact')], default='website', max_length=20, verbose_name='Source')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True, verbose_name='Last Contacted')),
                ('broker', models.ForeignKey(blank=True, limit_choices_to={'role': 'broker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokered_leads', to=settings.AUTH_USER_MODEL, verbose_name='Broker')),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='deals.lead', verbose_name='Lead'),
        ),
    ]
