# Generated by Django 4.2.27 on 2025-12-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('wire', 'Wire Transfer'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash'), ('crypto', 'Cryptocurrency'), ('financing', 'Financing')], max_length=20, null=True, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='deal',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('paid', 'Fully Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
    ]
