# Generated by Django 4.2.27 on 2025-12-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0002_deal_payment_method_deal_payment_status"),
    ]

    operations = [
        # Deal model indexes
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['status'], name='deals_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['-created_at'], name='deals_created_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['buyer'], name='deals_buyer_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['dealer'], name='deals_dealer_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['broker'], name='deals_broker_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['updated_at'], name='deals_updated_idx'),
        ),
        # Lead model indexes
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-created_at'], name='leads_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['buyer'], name='leads_buyer_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['updated_at'], name='leads_updated_idx'),
        ),
    ]
