# Generated by Django 4.2.27 on 2025-12-20 07:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("deals", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealFinancialTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Price"
                    ),
                ),
                (
                    "total_price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="For reporting and analytics",
                        max_digits=12,
                        verbose_name="Total Price (USD)",
                    ),
                ),
                (
                    "deposit_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        help_text="Percentage of total price required as deposit",
                        max_digits=5,
                        verbose_name="Deposit Percentage",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Deposit Amount"
                    ),
                ),
                (
                    "deposit_due_date",
                    models.DateTimeField(verbose_name="Deposit Due Date"),
                ),
                (
                    "deposit_paid",
                    models.BooleanField(default=False, verbose_name="Deposit Paid"),
                ),
                (
                    "deposit_paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deposit Paid At"
                    ),
                ),
                (
                    "balance_remaining",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Balance Remaining",
                    ),
                ),
                (
                    "balance_due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Balance Due Date"
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Paid",
                    ),
                ),
                (
                    "locked_exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Exchange rate locked at deal confirmation",
                        max_digits=12,
                        null=True,
                        verbose_name="Locked Exchange Rate",
                    ),
                ),
                (
                    "exchange_rate_locked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Exchange Rate Locked At"
                    ),
                ),
                (
                    "payment_term_days",
                    models.IntegerField(
                        default=30,
                        help_text="Days to pay full balance after deposit",
                        verbose_name="Payment Term Days",
                    ),
                ),
                (
                    "grace_period_days",
                    models.IntegerField(
                        default=3,
                        help_text="Grace period after due date before marked overdue",
                        verbose_name="Grace Period Days",
                    ),
                ),
                (
                    "is_financed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this deal involves financing",
                        verbose_name="Is Financed",
                    ),
                ),
                (
                    "deposit_refundable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether deposit can be refunded if deal cancelled",
                        verbose_name="Deposit Refundable",
                    ),
                ),
                (
                    "refund_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of deposit refundable",
                        max_digits=5,
                        verbose_name="Refund Percentage",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Financial Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Deal Financial Terms",
                "verbose_name_plural": "Deal Financial Terms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancingInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "installment_number",
                    models.IntegerField(verbose_name="Installment Number"),
                ),
                ("due_date", models.DateField(verbose_name="Due Date")),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount Due"
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Principal Amount"
                    ),
                ),
                (
                    "interest_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Interest Amount"
                    ),
                ),
                (
                    "late_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Late Fee",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Amount Paid",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid At"),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Remaining principal balance after this payment",
                        max_digits=12,
                        verbose_name="Remaining Balance",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("late", "Late"),
                            ("defaulted", "Defaulted"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("days_late", models.IntegerField(default=0, verbose_name="Days Late")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Financing Installment",
                "verbose_name_plural": "Financing Installments",
                "ordering": ["installment_number"],
            },
        ),
        migrations.CreateModel(
            name="FinancingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financing_type",
                    models.CharField(
                        choices=[
                            ("in_house", "In-House Financing"),
                            ("partner_lender", "Partner Lender"),
                            ("bank_loan", "Bank Loan"),
                            ("lease", "Lease-to-Own"),
                        ],
                        max_length=20,
                        verbose_name="Financing Type",
                    ),
                ),
                (
                    "lender_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Lender Name"
                    ),
                ),
                (
                    "lender_contact",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Lender Contact"
                    ),
                ),
                (
                    "financed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount being financed (balance after down payment)",
                        max_digits=12,
                        verbose_name="Financed Amount",
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Down Payment"
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate as percentage",
                        max_digits=5,
                        verbose_name="Interest Rate",
                    ),
                ),
                (
                    "term_months",
                    models.IntegerField(
                        help_text="Loan term in months (e.g., 12, 24, 36, 48, 60)",
                        verbose_name="Term (Months)",
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monthly Payment"
                    ),
                ),
                (
                    "total_interest",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Interest"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Financed amount + total interest",
                        max_digits=12,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("defaulted", "Defaulted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_approval",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "first_payment_date",
                    models.DateField(verbose_name="First Payment Date"),
                ),
                (
                    "final_payment_date",
                    models.DateField(verbose_name="Final Payment Date"),
                ),
                (
                    "credit_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Credit Score"
                    ),
                ),
                (
                    "credit_check_passed",
                    models.BooleanField(
                        default=False, verbose_name="Credit Check Passed"
                    ),
                ),
                (
                    "loan_agreement_url",
                    models.URLField(blank=True, verbose_name="Loan Agreement URL"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Financing Option",
                "verbose_name_plural": "Financing Options",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Initial Deposit"),
                            ("inspection", "Post-Inspection Payment"),
                            ("documentation", "Documentation Payment"),
                            ("pre_shipment", "Pre-Shipment Payment"),
                            ("delivery", "Final Delivery Payment"),
                            ("custom", "Custom Milestone"),
                        ],
                        max_length=20,
                        verbose_name="Milestone Type",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Milestone Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=1,
                        help_text="Order in payment schedule",
                        verbose_name="Sequence",
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount Due"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Amount Paid",
                    ),
                ),
                ("due_date", models.DateTimeField(verbose_name="Due Date")),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid At"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partially Paid"),
                            ("paid", "Fully Paid"),
                            ("overdue", "Overdue"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(default=False, verbose_name="Reminder Sent"),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reminder Sent At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Milestone",
                "verbose_name_plural": "Payment Milestones",
                "ordering": ["sequence", "due_date"],
            },
        ),
        migrations.RemoveIndex(
            model_name="deal",
            name="deals_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="deal",
            name="deals_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="deal",
            name="deals_buyer_idx",
        ),
        migrations.RemoveIndex(
            model_name="deal",
            name="deals_dealer_idx",
        ),
        migrations.RemoveIndex(
            model_name="deal",
            name="deals_broker_idx",
        ),
        migrations.RemoveIndex(
            model_name="deal",
            name="deals_updated_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="leads_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="leads_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="leads_buyer_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="leads_updated_idx",
        ),
        migrations.AddField(
            model_name="paymentmilestone",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.currency",
                verbose_name="Currency",
            ),
        ),
        migrations.AddField(
            model_name="paymentmilestone",
            name="deal_financial_terms",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="deals.dealfinancialterms",
                verbose_name="Deal Financial Terms",
            ),
        ),
        migrations.AddField(
            model_name="paymentmilestone",
            name="payments",
            field=models.ManyToManyField(
                blank=True,
                related_name="milestones",
                to="payments.payment",
                verbose_name="Payments",
            ),
        ),
        migrations.AddField(
            model_name="financingoption",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_financing",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved By",
            ),
        ),
        migrations.AddField(
            model_name="financingoption",
            name="deal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financing",
                to="deals.deal",
                verbose_name="Deal",
            ),
        ),
        migrations.AddField(
            model_name="financinginstallment",
            name="financing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installments",
                to="deals.financingoption",
                verbose_name="Financing Option",
            ),
        ),
        migrations.AddField(
            model_name="financinginstallment",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installments",
                to="payments.payment",
                verbose_name="Payment",
            ),
        ),
        migrations.AddField(
            model_name="dealfinancialterms",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.currency",
                verbose_name="Currency",
            ),
        ),
        migrations.AddField(
            model_name="dealfinancialterms",
            name="deal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_terms",
                to="deals.deal",
                verbose_name="Deal",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmilestone",
            index=models.Index(
                fields=["deal_financial_terms", "status"],
                name="deals_payme_deal_fi_214c08_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmilestone",
            index=models.Index(
                fields=["due_date", "status"], name="deals_payme_due_dat_0e8e31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financinginstallment",
            index=models.Index(
                fields=["financing", "status"], name="deals_finan_financi_52bda9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financinginstallment",
            index=models.Index(
                fields=["due_date", "status"], name="deals_finan_due_dat_a61c5c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="financinginstallment",
            unique_together={("financing", "installment_number")},
        ),
    ]
