# Generated by Django 4.2.27 on 2025-12-20 20:11

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0009_vehicle_lien_checked_vehicle_lien_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credit_tier",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent (750+)"),
                            ("good", "Good (650-749)"),
                            ("fair", "Fair (600-649)"),
                            ("poor", "Poor (550-599)"),
                            ("bad", "Bad (<550)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "loan_term_months",
                    models.IntegerField(
                        choices=[
                            (12, "12 months"),
                            (24, "24 months"),
                            (36, "36 months"),
                            (48, "48 months"),
                            (60, "60 months"),
                            (72, "72 months"),
                            (84, "84 months"),
                        ]
                    ),
                ),
                (
                    "annual_interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate percentage (e.g., 5.99 for 5.99%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("25.00")),
                        ],
                    ),
                ),
                ("effective_date", models.DateField(default=datetime.date.today)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "financing_interest_rates",
                "ordering": ["credit_tier", "loan_term_months"],
                "indexes": [
                    models.Index(
                        fields=["credit_tier", "loan_term_months"],
                        name="financing_i_credit__f86832_idx",
                    ),
                    models.Index(
                        fields=["is_active", "effective_date"],
                        name="financing_i_is_acti_91fc42_idx",
                    ),
                ],
                "unique_together": {
                    ("credit_tier", "loan_term_months", "effective_date")
                },
            },
        ),
        migrations.CreateModel(
            name="TradeInEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2030),
                        ]
                    ),
                ),
                ("make", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("trim", models.CharField(blank=True, max_length=50)),
                (
                    "mileage",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent - Like new, no visible wear"),
                            ("good", "Good - Minor cosmetic issues"),
                            ("fair", "Fair - Noticeable wear and tear"),
                            ("poor", "Poor - Significant damage or mechanical issues"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("province", models.CharField(default="ON", max_length=2)),
                (
                    "trade_in_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Dealer trade-in value",
                        max_digits=10,
                    ),
                ),
                (
                    "private_party_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Private sale value (higher)",
                        max_digits=10,
                    ),
                ),
                (
                    "retail_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Dealer retail value (highest)",
                        max_digits=10,
                    ),
                ),
                ("estimate_date", models.DateField(auto_now_add=True)),
                (
                    "data_source",
                    models.CharField(default="KBB Canada (Mock)", max_length=50),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_in_estimates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "financing_trade_in_estimates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["buyer", "-created_at"],
                        name="financing_t_buyer_i_0174df_idx",
                    ),
                    models.Index(
                        fields=["year", "make", "model"],
                        name="financing_t_year_db5138_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoanScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "trade_in_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "loan_term_months",
                    models.IntegerField(
                        choices=[
                            (12, "12 months"),
                            (24, "24 months"),
                            (36, "36 months"),
                            (48, "48 months"),
                            (60, "60 months"),
                            (72, "72 months"),
                            (84, "84 months"),
                        ],
                        default=48,
                    ),
                ),
                (
                    "credit_tier",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent (750+)"),
                            ("good", "Good (650-749)"),
                            ("fair", "Fair (600-649)"),
                            ("poor", "Poor (550-599)"),
                            ("bad", "Bad (<550)"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("province", models.CharField(default="ON", max_length=2)),
                (
                    "loan_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_interest",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "annual_interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "pst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "gst_hst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "documentation_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("500.00"), max_digits=10
                    ),
                ),
                (
                    "license_registration_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("120.00"), max_digits=10
                    ),
                ),
                (
                    "scenario_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name for this scenario",
                        max_length=100,
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_scenarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_scenarios",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "financing_loan_scenarios",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["buyer", "-created_at"],
                        name="financing_l_buyer_i_f34943_idx",
                    ),
                    models.Index(
                        fields=["vehicle"], name="financing_l_vehicle_e4073b_idx"
                    ),
                    models.Index(
                        fields=["is_favorite"], name="financing_l_is_favo_5e5d14_idx"
                    ),
                ],
            },
        ),
    ]
