# Generated by Django 6.0 on 2025-12-15 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True, verbose_name='Tracking Number')),
                ('shipping_company', models.CharField(max_length=255, verbose_name='Shipping Company')),
                ('origin_port', models.CharField(max_length=255, verbose_name='Origin Port')),
                ('destination_port', models.CharField(max_length=255, verbose_name='Destination Port')),
                ('destination_country', models.CharField(max_length=100, verbose_name='Destination Country')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('customs', 'At Customs'), ('delivered', 'Delivered'), ('delayed', 'Delayed')], default='pending', max_length=20, verbose_name='Status')),
                ('estimated_departure', models.DateField(blank=True, null=True, verbose_name='Estimated Departure')),
                ('actual_departure', models.DateField(blank=True, null=True, verbose_name='Actual Departure')),
                ('estimated_arrival', models.DateField(blank=True, null=True, verbose_name='Estimated Arrival')),
                ('actual_arrival', models.DateField(blank=True, null=True, verbose_name='Actual Arrival')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='deals.deal', verbose_name='Deal')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='shipments.shipment', verbose_name='Shipment')),
            ],
            options={
                'verbose_name': 'Shipment Update',
                'verbose_name_plural': 'Shipment Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
