# Generated by Django 4.2.27 on 2025-12-16 23:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Current Latitude'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Current Longitude'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Location Update'),
        ),
        migrations.CreateModel(
            name='ShipmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='shipments/photos/%Y/%m/%d/', verbose_name='Photo')),
                ('photo_type', models.CharField(choices=[('loading', 'Loading'), ('in_transit', 'In Transit'), ('arrival', 'Arrival'), ('customs', 'Customs'), ('delivery', 'Delivery'), ('damage', 'Damage Report'), ('other', 'Other')], default='other', max_length=50, verbose_name='Photo Type')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Taken At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shipments.shipment', verbose_name='Shipment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Shipment Photo',
                'verbose_name_plural': 'Shipment Photos',
                'ordering': ['-taken_at', '-created_at'],
                'indexes': [models.Index(fields=['shipment', '-created_at'], name='shipments_s_shipmen_f54e6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShipmentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('pickup', 'Vehicle Picked Up'), ('departed_origin', 'Departed Origin Port'), ('in_transit', 'In Transit'), ('arrived_port', 'Arrived at Destination Port'), ('customs_clearance', 'Customs Clearance'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered to Buyer')], max_length=50, verbose_name='Milestone Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='shipments.shipment', verbose_name='Shipment')),
            ],
            options={
                'verbose_name': 'Shipment Milestone',
                'verbose_name_plural': 'Shipment Milestones',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['shipment', 'order'], name='shipments_s_shipmen_dedee6_idx'), models.Index(fields=['shipment', 'is_completed'], name='shipments_s_shipmen_8221bc_idx')],
            },
        ),
    ]
