# Generated by Django 4.2.27 on 2025-12-16 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Company Name"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Address"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postal Code"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Phone"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Settings",
                "verbose_name_plural": "Company Settings",
            },
        ),
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cad_to_xof",
                    models.DecimalField(
                        decimal_places=2,
                        default=450.0,
                        help_text="How many XOF equals 1 CAD",
                        max_digits=10,
                        verbose_name="CAD to XOF Rate",
                    ),
                ),
                (
                    "xof_to_cad",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0022,
                        help_text="How many CAD equals 1 XOF",
                        max_digits=10,
                        verbose_name="XOF to CAD Rate",
                    ),
                ),
                (
                    "auto_update",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically refresh rates daily",
                        verbose_name="Auto Update",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Updated"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Currency Rate",
                "verbose_name_plural": "Currency Rates",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("export", "Export"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Model Name"),
                ),
                (
                    "object_id",
                    models.CharField(max_length=100, verbose_name="Object ID"),
                ),
                ("object_repr", models.TextField(verbose_name="Object Representation")),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON of field changes",
                        verbose_name="Changes",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="nzila_expor_user_id_1bdd46_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="nzila_expor_model_n_b6893c_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="nzila_expor_action_4ddbd1_idx",
                    ),
                ],
            },
        ),
    ]
