# Generated by Django 4.2.27 on 2025-12-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nzila_export', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompanySettings',
        ),
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
