# Generated by Django 4.2.27 on 2025-12-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(default=False, verbose_name="Phone Verified"),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stripe Customer ID"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(default=False, verbose_name="2FA Enabled"),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_secret",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="2FA Secret"
            ),
        ),
    ]
