# Generated by Django 4.2.27 on 2025-12-17 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_verified_user_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_category', models.CharField(choices=[('user_profile', 'User Profile Information'), ('financial', 'Financial Records (7 years)'), ('vehicle_listings', 'Vehicle Listings'), ('deals_transactions', 'Deals and Transactions (7 years)'), ('commissions', 'Commission Records (7 years)'), ('audit_logs', 'Audit Logs (7 years)'), ('marketing', 'Marketing Communications'), ('support_tickets', 'Customer Support Records'), ('shipping_documents', 'Shipping Documents (7 years)'), ('customs_certifications', 'Customs/Certification Records (7 years)'), ('session_logs', 'Session Logs (90 days)'), ('analytics', 'Analytics Data (2 years)')], max_length=50, unique=True, verbose_name='Data Category')),
                ('retention_days', models.IntegerField(help_text='Number of days to retain data (2555 days = 7 years)', verbose_name='Retention Period (Days)')),
                ('legal_basis', models.TextField(help_text='Legal requirement for retention period (e.g., CRA, Tax Act)', verbose_name='Legal Basis')),
                ('auto_delete_enabled', models.BooleanField(default=False, help_text='Automatically delete data after retention period', verbose_name='Auto-Delete Enabled')),
                ('last_cleanup_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Cleanup Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Retention Policy',
                'verbose_name_plural': 'Data Retention Policies',
                'ordering': ['data_category'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='consent_date',
            field=models.DateTimeField(blank=True, help_text='Date when user provided explicit consent', null=True, verbose_name='Consent Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which consent was provided (audit trail)', null=True, verbose_name='Consent IP Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_version',
            field=models.CharField(blank=True, default='1.0', help_text='Version of privacy policy user consented to', max_length=20, verbose_name='Consent Version'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_deletion_requested_date',
            field=models.DateTimeField(blank=True, help_text='When user requested account deletion (Law 25 Article 28)', null=True, verbose_name='Data Deletion Requested'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_export_requested_date',
            field=models.DateTimeField(blank=True, help_text='When user requested data export (Law 25 Article 8.5)', null=True, verbose_name='Data Export Requested'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_processing_consent',
            field=models.BooleanField(default=False, help_text='User has consented to processing of personal information (PIPEDA Principle 3)', verbose_name='Data Processing Consent'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_rectification_requested_date',
            field=models.DateTimeField(blank=True, help_text='When user requested data correction', null=True, verbose_name='Data Rectification Requested'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_transfer_consent_africa',
            field=models.BooleanField(default=False, help_text='Consent for transferring personal info to African brokers (PIPEDA Principle 4.1.3)', verbose_name='Africa Data Transfer Consent'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='User has consented to receive marketing communications (Law 25 Article 8)', verbose_name='Marketing Communications Consent'),
        ),
        migrations.AddField(
            model_name='user',
            name='third_party_sharing_consent',
            field=models.BooleanField(default=False, help_text='User has consented to sharing data with brokers/partners across borders', verbose_name='Third Party Sharing Consent'),
        ),
        migrations.CreateModel(
            name='PrivacyImpactAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Assessment Title')),
                ('description', models.TextField(help_text='Description of system/process being assessed', verbose_name='Description')),
                ('project_name', models.CharField(blank=True, max_length=255, verbose_name='Project Name')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], default='medium', max_length=20, verbose_name='Risk Level')),
                ('data_types_processed', models.JSONField(default=list, help_text='List of personal information types processed', verbose_name='Data Types Processed')),
                ('cross_border_transfer', models.BooleanField(default=False, help_text='Does this involve transferring data outside Canada?', verbose_name='Cross-Border Transfer')),
                ('identified_risks', models.TextField(verbose_name='Identified Risks')),
                ('mitigation_measures', models.TextField(verbose_name='Mitigation Measures')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_revision', 'Requires Revision')], default='draft', max_length=20, verbose_name='Status')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_due_date', models.DateField(blank=True, help_text='When this PIA should be reviewed (typically annually)', null=True, verbose_name='Review Due Date')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pias', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_pias', to=settings.AUTH_USER_MODEL, verbose_name='Assessed By')),
            ],
            options={
                'verbose_name': 'Privacy Impact Assessment',
                'verbose_name_plural': 'Privacy Impact Assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataBreachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breach_date', models.DateTimeField(help_text='When the breach occurred (estimated if unknown)', verbose_name='Breach Date')),
                ('discovery_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the breach was discovered', verbose_name='Discovery Date')),
                ('severity', models.CharField(choices=[('low', 'Low - No significant risk'), ('medium', 'Medium - Moderate risk'), ('high', 'High - Real risk of serious harm'), ('critical', 'Critical - Immediate serious harm')], default='medium', max_length=20, verbose_name='Severity Level')),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('investigating', 'Investigating'), ('users_notified', 'Users Notified'), ('authorities_notified', 'Authorities Notified'), ('cai_notified', 'CAI Notified (Quebec)'), ('opc_notified', 'OPC Notified (Federal)'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved')], default='discovered', max_length=30, verbose_name='Status')),
                ('affected_users_count', models.IntegerField(default=0, verbose_name='Number of Affected Users')),
                ('data_types_compromised', models.JSONField(default=list, help_text='List of data types: email, phone, address, financial, etc.', verbose_name='Data Types Compromised')),
                ('description', models.TextField(help_text='Detailed description of what happened', verbose_name='Breach Description')),
                ('attack_vector', models.CharField(blank=True, help_text='How the breach occurred: phishing, SQL injection, etc.', max_length=100, verbose_name='Attack Vector')),
                ('users_notified_date', models.DateTimeField(blank=True, null=True, verbose_name='Users Notified Date')),
                ('cai_notified_date', models.DateTimeField(blank=True, help_text="Commission d'accès à l'information du Québec", null=True, verbose_name='CAI Notified Date')),
                ('opc_notified_date', models.DateTimeField(blank=True, help_text='Office of the Privacy Commissioner of Canada', null=True, verbose_name='OPC Notified Date')),
                ('mitigation_steps', models.TextField(blank=True, help_text='Steps taken to address the breach', verbose_name='Mitigation Steps')),
                ('resolution_date', models.DateTimeField(blank=True, null=True, verbose_name='Resolution Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_users', models.ManyToManyField(blank=True, related_name='data_breaches', to=settings.AUTH_USER_MODEL, verbose_name='Affected Users')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_breaches', to=settings.AUTH_USER_MODEL, verbose_name='Reported By')),
            ],
            options={
                'verbose_name': 'Data Breach Log',
                'verbose_name_plural': 'Data Breach Logs',
                'ordering': ['-discovery_date'],
            },
        ),
        migrations.CreateModel(
            name='ConsentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('data_processing', 'Data Processing'), ('marketing', 'Marketing Communications'), ('third_party_sharing', 'Third Party Sharing'), ('cross_border_africa', 'Cross-Border Transfer to Africa'), ('cookies', 'Cookie Consent'), ('analytics', 'Analytics Tracking')], max_length=50, verbose_name='Consent Type')),
                ('action', models.CharField(choices=[('granted', 'Consent Granted'), ('withdrawn', 'Consent Withdrawn'), ('modified', 'Consent Modified'), ('renewed', 'Consent Renewed')], max_length=20, verbose_name='Action')),
                ('consent_given', models.BooleanField(verbose_name='Consent Given')),
                ('privacy_policy_version', models.CharField(max_length=20, verbose_name='Privacy Policy Version')),
                ('consent_method', models.CharField(default='web_form', help_text='How consent was collected: web_form, email, phone, in_person', max_length=50, verbose_name='Consent Method')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('consent_text', models.TextField(blank=True, help_text='Exact text user consented to', verbose_name='Consent Text Shown')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Consent History',
                'verbose_name_plural': 'Consent Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='accounts_co_user_id_6cd7db_idx'), models.Index(fields=['consent_type', '-timestamp'], name='accounts_co_consent_f3ac99_idx')],
            },
        ),
    ]
