# Generated by Django 4.2.27 on 2025-12-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_dataretentionpolicy_user_consent_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allows_test_drives",
            field=models.BooleanField(default=True, verbose_name="Allows Test Drives"),
        ),
        migrations.AddField(
            model_name="user",
            name="business_hours",
            field=models.TextField(
                blank=True,
                help_text="Mon-Fri 9am-6pm, Sat 10am-4pm, etc.",
                verbose_name="Business Hours",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="buyer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("personal", "Personal Use"),
                    ("family", "Gift for Family"),
                    ("business", "Business/Resale"),
                ],
                max_length=20,
                verbose_name="Purchase Purpose",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="canadian_city",
            field=models.CharField(
                blank=True,
                help_text="Toronto, Vancouver, Calgary, Montreal, etc.",
                max_length=100,
                verbose_name="City",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="canadian_postal_code",
            field=models.CharField(
                blank=True,
                help_text="A1A 1A1 format",
                max_length=7,
                verbose_name="Postal Code",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="canadian_province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ON", "Ontario"),
                    ("QC", "Quebec"),
                    ("BC", "British Columbia"),
                    ("AB", "Alberta"),
                    ("MB", "Manitoba"),
                    ("SK", "Saskatchewan"),
                    ("NS", "Nova Scotia"),
                    ("NB", "New Brunswick"),
                    ("NL", "Newfoundland and Labrador"),
                    ("PE", "Prince Edward Island"),
                    ("NT", "Northwest Territories"),
                    ("NU", "Nunavut"),
                    ("YT", "Yukon"),
                ],
                max_length=2,
                verbose_name="Province/Territory",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="destination_city",
            field=models.CharField(
                blank=True,
                help_text="Lagos, Accra, Nairobi, etc.",
                max_length=100,
                verbose_name="Destination City",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="destination_country",
            field=models.CharField(
                blank=True,
                help_text="Where vehicle will be shipped (Nigeria, Ghana, Kenya, etc.)",
                max_length=100,
                verbose_name="Destination Country",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_diaspora_buyer",
            field=models.BooleanField(
                default=False,
                help_text="Buyer resides in Canada, purchasing for export to Africa",
                verbose_name="Canadian Diaspora Buyer",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="local_phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Local Phone Number"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_support_hours",
            field=models.TextField(blank=True, verbose_name="Phone Support Hours"),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("phone", "Phone Call"),
                    ("sms", "Text/SMS"),
                    ("whatsapp", "WhatsApp"),
                    ("email", "Email"),
                    ("chat", "Live Chat"),
                ],
                max_length=20,
                verbose_name="Preferred Contact Method",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="prefers_in_person_inspection",
            field=models.BooleanField(
                default=False,
                help_text="Buyer wants to physically inspect vehicles before purchase",
                verbose_name="Prefers In-Person Inspection",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="requires_appointment",
            field=models.BooleanField(
                default=False,
                help_text="Buyers must book appointment before visiting",
                verbose_name="Requires Appointment",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="residency_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("citizen", "Canadian Citizen"),
                    ("pr", "Permanent Resident"),
                    ("work_permit", "Work Permit"),
                    ("study_permit", "Study Permit"),
                    ("visitor", "Visitor/Tourist"),
                ],
                max_length=20,
                verbose_name="Canadian Residency Status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="showroom_address",
            field=models.TextField(
                blank=True,
                help_text="Physical address where buyers can view vehicles",
                verbose_name="Showroom Address",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="showroom_city",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Showroom City"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="showroom_phone",
            field=models.CharField(
                blank=True,
                help_text="Direct phone for showroom/inspection bookings",
                max_length=20,
                verbose_name="Showroom Phone",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="showroom_postal_code",
            field=models.CharField(
                blank=True, max_length=7, verbose_name="Showroom Postal Code"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="showroom_province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ON", "Ontario"),
                    ("QC", "Quebec"),
                    ("BC", "British Columbia"),
                    ("AB", "Alberta"),
                    ("MB", "Manitoba"),
                    ("SK", "Saskatchewan"),
                    ("NS", "Nova Scotia"),
                    ("NB", "New Brunswick"),
                    ("NL", "Newfoundland and Labrador"),
                    ("PE", "Prince Edward Island"),
                    ("NT", "Northwest Territories"),
                    ("NU", "Nunavut"),
                    ("YT", "Yukon"),
                ],
                max_length=2,
                verbose_name="Showroom Province",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="toll_free_number",
            field=models.CharField(
                blank=True,
                help_text="1-800-XXX-XXXX format",
                max_length=20,
                verbose_name="Toll-Free Number",
            ),
        ),
    ]
