# Generated by Django 4.2.27 on 2025-12-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_allows_test_drives_user_business_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Receive email notifications",
                verbose_name="Email Notifications",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_frequency",
            field=models.CharField(
                choices=[
                    ("instant", "Instant"),
                    ("hourly", "Hourly Digest"),
                    ("daily", "Daily Digest"),
                    ("weekly", "Weekly Digest"),
                    ("never", "Never"),
                ],
                default="instant",
                help_text="How often to receive non-critical notifications",
                max_length=20,
                verbose_name="Notification Frequency",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="push_notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Receive browser/app push notifications",
                verbose_name="Push Notifications",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sms_notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Receive SMS for critical updates (offers, payments, shipments)",
                verbose_name="SMS Notifications",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp_notifications_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Receive WhatsApp messages (requires WhatsApp number)",
                verbose_name="WhatsApp Notifications",
            ),
        ),
    ]
