# Generated by Django 4.2.27 on 2025-12-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_notification_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="City for proximity search (Canadian buyers)",
                max_length=100,
                verbose_name="City",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude for proximity search",
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude for proximity search",
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_code",
            field=models.CharField(
                blank=True,
                help_text="Canadian postal code (e.g., M5H 2N2)",
                max_length=7,
                verbose_name="Postal Code",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ON", "Ontario"),
                    ("QC", "Quebec"),
                    ("BC", "British Columbia"),
                    ("AB", "Alberta"),
                    ("MB", "Manitoba"),
                    ("SK", "Saskatchewan"),
                    ("NS", "Nova Scotia"),
                    ("NB", "New Brunswick"),
                    ("NL", "Newfoundland and Labrador"),
                    ("PE", "Prince Edward Island"),
                    ("NT", "Northwest Territories"),
                    ("YT", "Yukon"),
                    ("NU", "Nunavut"),
                ],
                help_text="Province for proximity search and timezone display",
                max_length=2,
                verbose_name="Province",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="travel_radius_km",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (50, "50 km"),
                    (100, "100 km"),
                    (200, "200 km"),
                    (500, "Province-wide"),
                    (1000, "All of Canada"),
                ],
                help_text="Maximum distance willing to travel to view vehicles",
                null=True,
                verbose_name="Travel Radius",
            ),
        ),
    ]
