# Generated by Django 4.2.27 on 2025-12-21 04:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_buyer_location_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealerVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Verification Pending"),
                            ("verified", "Verified"),
                            ("suspended", "Suspended"),
                        ],
                        default="unverified",
                        max_length=20,
                        verbose_name="Verification Status",
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        choices=[
                            ("none", "No Badge"),
                            ("bronze", "Bronze Badge"),
                            ("silver", "Silver Badge"),
                            ("gold", "Gold Badge"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Badge Level",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Legal Business Name"
                    ),
                ),
                (
                    "business_number",
                    models.CharField(
                        blank=True,
                        help_text="CRA Business Number (BN)",
                        max_length=50,
                        verbose_name="Business Number",
                    ),
                ),
                (
                    "years_in_business",
                    models.IntegerField(default=0, verbose_name="Years in Business"),
                ),
                (
                    "business_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Business Start Date"
                    ),
                ),
                (
                    "has_insurance",
                    models.BooleanField(
                        default=False, verbose_name="Has Business Insurance"
                    ),
                ),
                (
                    "insurance_provider",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Insurance Provider"
                    ),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Policy Number"
                    ),
                ),
                (
                    "insurance_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="Insurance Expiry Date"
                    ),
                ),
                (
                    "total_sales",
                    models.IntegerField(
                        default=0,
                        help_text="Total vehicles sold on platform",
                        verbose_name="Total Sales",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total transaction value",
                        max_digits=12,
                        verbose_name="Total Revenue (CAD)",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average review rating (0-5)",
                        max_digits=3,
                        verbose_name="Average Rating",
                    ),
                ),
                (
                    "total_reviews",
                    models.IntegerField(default=0, verbose_name="Total Reviews"),
                ),
                (
                    "trust_score",
                    models.IntegerField(
                        default=0,
                        help_text="Calculated trust score (0-100)",
                        verbose_name="Trust Score",
                    ),
                ),
                (
                    "license_verified",
                    models.BooleanField(default=False, verbose_name="License Verified"),
                ),
                (
                    "insurance_verified",
                    models.BooleanField(
                        default=False, verbose_name="Insurance Verified"
                    ),
                ),
                (
                    "business_verified",
                    models.BooleanField(
                        default=False, verbose_name="Business Number Verified"
                    ),
                ),
                (
                    "identity_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Government ID verified",
                        verbose_name="Identity Verified",
                    ),
                ),
                (
                    "address_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Business address verified",
                        verbose_name="Address Verified",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Admin Notes")),
                (
                    "dealer",
                    models.OneToOneField(
                        limit_choices_to={"role": "dealer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dealer",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_dealers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealer Verification",
                "verbose_name_plural": "Dealer Verifications",
            },
        ),
        migrations.CreateModel(
            name="DealerLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("omvic", "OMVIC - Ontario Motor Vehicle Industry Council"),
                            ("amvic", "AMVIC - Alberta Motor Vehicle Industry Council"),
                            (
                                "saaq",
                                "SAAQ - Société de l'assurance automobile du Québec",
                            ),
                            ("mvdb", "MVDB - Motor Vehicle Dealers Board (BC)"),
                            ("mgi", "MGI - Manitoba Government Insurance"),
                            ("sgi", "SGI - Saskatchewan Government Insurance"),
                            ("snsmr", "SNS - Service Nova Scotia Motor Registration"),
                            ("snb", "SNB - Service New Brunswick"),
                            ("business", "Business License"),
                            ("gst", "GST/HST Registration"),
                            ("pst", "PST Registration"),
                            ("other", "Other License/Certification"),
                        ],
                        max_length=20,
                        verbose_name="License Type",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        help_text="Official license/registration number",
                        max_length=100,
                        verbose_name="License Number",
                    ),
                ),
                (
                    "issuing_authority",
                    models.CharField(
                        help_text="Organization that issued the license",
                        max_length=200,
                        verbose_name="Issuing Authority",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ON", "Ontario"),
                            ("QC", "Quebec"),
                            ("BC", "British Columbia"),
                            ("AB", "Alberta"),
                            ("MB", "Manitoba"),
                            ("SK", "Saskatchewan"),
                            ("NS", "Nova Scotia"),
                            ("NB", "New Brunswick"),
                            ("NL", "Newfoundland and Labrador"),
                            ("PE", "Prince Edward Island"),
                            ("NT", "Northwest Territories"),
                            ("YT", "Yukon"),
                            ("NU", "Nunavut"),
                        ],
                        max_length=2,
                        verbose_name="Province/Territory",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Issue Date")),
                ("expiry_date", models.DateField(verbose_name="Expiry Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("expired", "Expired"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Upload scanned copy of license",
                        null=True,
                        upload_to="dealer_licenses/%Y/%m/",
                        verbose_name="License Document",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Admin Notes")),
                (
                    "dealer",
                    models.ForeignKey(
                        limit_choices_to={"role": "dealer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dealer",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_licenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealer License",
                "verbose_name_plural": "Dealer Licenses",
                "ordering": ["-created_at"],
                "unique_together": {("dealer", "license_type", "license_number")},
            },
        ),
    ]
