# Generated by Django 4.2.27 on 2025-12-20 19:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0009_vehicle_lien_checked_vehicle_lien_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CBSA_FORM_1", "CBSA Form 1 - Vehicle Export Declaration"),
                            ("TITLE_GUIDE_ON", "Ontario Title Transfer Guide"),
                            ("TITLE_GUIDE_QC", "Quebec Title Transfer Guide"),
                            ("TITLE_GUIDE_BC", "British Columbia Title Transfer Guide"),
                            ("TITLE_GUIDE_AB", "Alberta Title Transfer Guide"),
                            ("TITLE_GUIDE_MB", "Manitoba Title Transfer Guide"),
                            ("TITLE_GUIDE_SK", "Saskatchewan Title Transfer Guide"),
                            ("TITLE_GUIDE_NS", "Nova Scotia Title Transfer Guide"),
                            ("TITLE_GUIDE_NB", "New Brunswick Title Transfer Guide"),
                            (
                                "TITLE_GUIDE_NL",
                                "Newfoundland & Labrador Title Transfer Guide",
                            ),
                            (
                                "TITLE_GUIDE_PE",
                                "Prince Edward Island Title Transfer Guide",
                            ),
                            (
                                "TITLE_GUIDE_NT",
                                "Northwest Territories Title Transfer Guide",
                            ),
                            ("TITLE_GUIDE_YT", "Yukon Title Transfer Guide"),
                            ("TITLE_GUIDE_NU", "Nunavut Title Transfer Guide"),
                            ("LIEN_CERTIFICATE", "PPSA Lien Search Certificate"),
                            ("EXPORT_CHECKLIST", "Export Readiness Checklist"),
                            ("BILL_OF_SALE", "Bill of Sale"),
                            ("OTHER", "Other Document"),
                        ],
                        max_length=50,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="export_documents/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx", "jpg", "png"]
                            )
                        ],
                        verbose_name="Document File",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Generation"),
                            ("GENERATED", "Generated"),
                            ("DELIVERED", "Delivered to Buyer"),
                            ("EXPIRED", "Expired"),
                            ("FAILED", "Generation Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when document becomes invalid (e.g., CBSA forms valid 30 days)",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional information or generation errors",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Buyer",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_documents",
                        to="vehicles.vehicle",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Document",
                "verbose_name_plural": "Export Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "document_type"],
                        name="documents_e_vehicle_1fbe9d_idx",
                    ),
                    models.Index(
                        fields=["buyer", "created_at"],
                        name="documents_e_buyer_i_c41a56_idx",
                    ),
                    models.Index(
                        fields=["status"], name="documents_e_status_facbbc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExportChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Vehicle title is clear and verified",
                        verbose_name="Title Verified",
                    ),
                ),
                (
                    "lien_checked",
                    models.BooleanField(
                        default=False,
                        help_text="PPSA lien search completed with no active liens",
                        verbose_name="Lien Search Completed",
                    ),
                ),
                (
                    "insurance_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Export insurance coverage confirmed",
                        verbose_name="Insurance Confirmed",
                    ),
                ),
                (
                    "payment_cleared",
                    models.BooleanField(
                        default=False,
                        help_text="Payment received and cleared",
                        verbose_name="Payment Cleared",
                    ),
                ),
                (
                    "inspection_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Third-party inspection completed (if required)",
                        verbose_name="Inspection Completed",
                    ),
                ),
                (
                    "cbsa_form_generated",
                    models.BooleanField(
                        default=False,
                        help_text="CBSA Form 1 vehicle export declaration generated",
                        verbose_name="CBSA Form 1 Generated",
                    ),
                ),
                (
                    "title_guide_provided",
                    models.BooleanField(
                        default=False,
                        help_text="Provincial title transfer guide provided to buyer",
                        verbose_name="Title Guide Provided",
                    ),
                ),
                (
                    "export_ready",
                    models.BooleanField(
                        default=False,
                        help_text="All checklist items completed, vehicle ready for export",
                        verbose_name="Export Ready",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When all checklist items were completed",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or issues",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_checklists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Buyer",
                    ),
                ),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_checklist",
                        to="vehicles.vehicle",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Checklist",
                "verbose_name_plural": "Export Checklists",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vehicle"], name="documents_e_vehicle_83df24_idx"
                    ),
                    models.Index(
                        fields=["buyer", "export_ready"],
                        name="documents_e_buyer_i_f21af6_idx",
                    ),
                ],
            },
        ),
    ]
