# Generated by Django 4.2.27 on 2025-12-16 23:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0004_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('vehicle', 'Vehicle Review'), ('dealer', 'Dealer Review'), ('platform', 'Platform Review')], default='vehicle', max_length=20, verbose_name='Review Type')),
                ('rating', models.IntegerField(help_text='1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Overall Rating')),
                ('title', models.CharField(max_length=200, verbose_name='Review Title')),
                ('comment', models.TextField(help_text='Share your experience', verbose_name='Review Comment')),
                ('vehicle_condition_rating', models.IntegerField(blank=True, help_text='How accurate was the vehicle description?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Vehicle Condition')),
                ('communication_rating', models.IntegerField(blank=True, help_text='How responsive was the dealer?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Communication')),
                ('delivery_rating', models.IntegerField(blank=True, help_text='Was delivery timely and professional?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Delivery')),
                ('value_rating', models.IntegerField(blank=True, help_text='Was the vehicle worth the price?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Value for Money')),
                ('buyer_location', models.CharField(blank=True, help_text='City, Country (optional)', max_length=100, verbose_name='Buyer Location')),
                ('would_recommend', models.BooleanField(default=True, help_text='Would you recommend this dealer?', verbose_name='Would Recommend')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Review from actual buyer', verbose_name='Verified Purchase')),
                ('is_approved', models.BooleanField(default=True, help_text='Moderation status', verbose_name='Approved')),
                ('is_featured', models.BooleanField(default=False, help_text='Showcase this review', verbose_name='Featured')),
                ('dealer_response', models.TextField(blank=True, help_text='Dealer can respond to review', verbose_name='Dealer Response')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Response Date')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Helpful Count')),
                ('not_helpful_count', models.IntegerField(default=0, verbose_name='Not Helpful Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('dealer', models.ForeignKey(limit_choices_to={'role': 'dealer'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Dealer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('five_star_count', models.IntegerField(default=0)),
                ('four_star_count', models.IntegerField(default=0)),
                ('three_star_count', models.IntegerField(default=0)),
                ('two_star_count', models.IntegerField(default=0)),
                ('one_star_count', models.IntegerField(default=0)),
                ('avg_vehicle_condition', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('avg_communication', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('avg_delivery', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('avg_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('recommend_count', models.IntegerField(default=0)),
                ('recommend_percentage', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dealer', models.OneToOneField(limit_choices_to={'role': 'dealer'}, on_delete=django.db.models.deletion.CASCADE, related_name='rating_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dealer Rating Statistics',
                'verbose_name_plural': 'Dealer Rating Statistics',
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpfulness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(verbose_name='Is Helpful')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpfulness_votes', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Helpfulness Vote',
                'verbose_name_plural': 'Review Helpfulness Votes',
                'unique_together': {('review', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['dealer', 'is_approved'], name='reviews_rev_dealer__09b537_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['vehicle', 'is_approved'], name='reviews_rev_vehicle_6cdc29_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('buyer', 'vehicle'), name='unique_buyer_vehicle_review'),
        ),
    ]
