"""
Django settings for nzila_export project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default='False', cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Frontend URL for email links
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:5174',
    'http://localhost:5175',
    'http://localhost:5176',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:5174',
    'http://127.0.0.1:5175',
    'http://127.0.0.1:5176',
    'http://localhost:3000',
    'http://localhost:3001',
]
CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    'daphne',  # Django Channels ASGI server - must be before django.contrib.staticfiles
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',  # Django Channels for WebSockets
    'corsheaders',
    'rest_framework',
    'django_filters',
    # Development tools (only enabled if DEBUG=True)
    'debug_toolbar',
    # Project apps
    'nzila_export',
    'accounts',
    'vehicles',
    'deals',
    'shipments',
    'commissions',
    'analytics',
    'notifications',
    'payments',
    'audit',
    'favorites',
    'email_templates',
    'saved_searches',
    'price_alerts',
    'recommendations',
    'vehicle_history',
    'analytics_dashboard',
    'chat',
    'reviews',
    'documents',  # PHASE 2 - Feature 5: Export Documentation
    'inspections',  # PHASE 2 - Feature 6: Third-Party Inspection Integration
    'financing',  # PHASE 3 - Feature 7: Financing Calculator Enhancement
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Django Debug Toolbar middleware (only active if DEBUG=True and INTERNAL_IPS match)
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Audit middleware
    'audit.middleware.AuditMiddleware',
    'audit.middleware.SecurityAuditMiddleware',
]

ROOT_URLCONF = 'nzila_export.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'nzila_export.wsgi.application'

# ASGI Application (Django Channels for WebSockets)
ASGI_APPLICATION = 'nzila_export.asgi_channels.application'

# Django Channels Configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(os.environ.get('REDIS_HOST', '127.0.0.1'), 6379)],
            "capacity": 1500,  # Max messages in channel before blocking
            "expiry": 10,  # Message expiry in seconds
        },
    },
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # Connection pooling settings
        'CONN_MAX_AGE': 600,  # Keep connections alive for 10 minutes
        'CONN_HEALTH_CHECKS': True,  # Check connection health before using
        'OPTIONS': {
            'timeout': 20,  # Database timeout in seconds
        },
    }
}

# PostgreSQL SSL Configuration (Production)
# Override DATABASES in production settings to include:
# 'OPTIONS': {
#     'sslmode': 'require',
#     'sslrootcert': '/path/to/root.crt',
#     'sslcert': '/path/to/client.crt',
#     'sslkey': '/path/to/client.key',
# }


# Cache Configuration
# Using Redis for production-grade caching (shared across workers, persistent)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'SOCKET_CONNECT_TIMEOUT': 5,  # seconds
            'SOCKET_TIMEOUT': 5,  # seconds
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'IGNORE_EXCEPTIONS': True,  # Don't crash if Redis is down
        },
        'KEY_PREFIX': 'nzila',
        'TIMEOUT': 3600,  # Default: 1 hour
    }
}

# Cache key timeouts for different data types
CACHE_TTL = {
    'vehicle_list': 60 * 15,  # 15 minutes
    'vehicle_detail': 60 * 60,  # 1 hour
    'carfax_report': 60 * 60 * 24,  # 24 hours (expensive API)
    'exchange_rates': 60 * 60 * 12,  # 12 hours
    'dealer_performance': 60 * 30,  # 30 minutes
    'analytics_dashboard': 60 * 15,  # 15 minutes
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('fr', 'Français'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'America/Toronto'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.JWTCookieAuthentication',  # Custom cookie-based JWT
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # API Rate Limiting - Production Security Settings
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # Anonymous users: 0.03 req/sec (realistic browsing)
        'user': '1000/hour',  # Authenticated users: 0.28 req/sec (normal API usage)
        'payment': '10/hour',  # Payment endpoints: Max 10 payment attempts/hour
        'login': '5/minute',  # Login attempts: 5/min to prevent credential stuffing
        'registration': '3/hour',  # User registration: Prevent bot signups
        'password_reset': '3/hour',  # Password reset: Prevent email bombing
        'vehicle_history': '50/hour',  # CarFax/AutoCheck API calls (reduced costs)
        'transport_canada': '500/hour',  # Transport Canada public data
        'provincial_registry': '50/hour',  # Provincial registry APIs
    },
}

# Stripe Payment Configuration
# Stripe Payment Configuration
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

# Twilio SMS Configuration (for 2FA)
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default='')

# Multi-Currency Configuration
DEFAULT_CURRENCY = config('DEFAULT_CURRENCY', default='USD')
SUPPORTED_CURRENCIES = config('SUPPORTED_CURRENCIES', cast=Csv(), 
                             default='USD,EUR,GBP,ZAR,NGN,KES,GHS,EGP')

# African Payment Gateways (Optional)
FLUTTERWAVE_SECRET_KEY = config('FLUTTERWAVE_SECRET_KEY', default='')
FLUTTERWAVE_PUBLIC_KEY = config('FLUTTERWAVE_PUBLIC_KEY', default='')
CARFAX_API_URL = config('CARFAX_API_URL', default='https://api.carfax.com/v1')
CARFAX_CACHE_TTL = config('CARFAX_CACHE_TTL', default=604800, cast=int)  # 7 days
AUTOCHECK_API_KEY = config('AUTOCHECK_API_KEY', default=None)
ICBC_API_KEY = config('ICBC_API_KEY', default=None)  # British Columbia
MTO_API_KEY = config('MTO_API_KEY', default=None)  # Ontario
SAAQ_API_KEY = config('SAAQ_API_KEY', default=None)  # Quebec

# WhatsApp Business API Configuration
WHATSAPP_API_TOKEN = config('WHATSAPP_API_TOKEN', default=None)
WHATSAPP_PHONE_NUMBER_ID = config('WHATSAPP_PHONE_NUMBER_ID', default=None)
WHATSAPP_VERIFY_TOKEN = config('WHATSAPP_VERIFY_TOKEN', default=None)

# ============================================================================
# EMAIL CONFIGURATION
# ============================================================================

# Email Backend Configuration
# Options: 'django.core.mail.backends.console.EmailBackend' (development)
#         'django.core.mail.backends.smtp.EmailBackend' (production)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')

# SMTP Settings (for production with SendGrid or AWS SES)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.sendgrid.net')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='apikey')  # 'apikey' for SendGrid
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default=None)  # SendGrid API key or SMTP password

# From Addresses
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@nzilaventures.com')
ADMIN_EMAIL = config('ADMIN_EMAIL', default='info@nzilaventures.com')
SUPPORT_EMAIL = config('SUPPORT_EMAIL', default='support@nzilaventures.com')
PRIVACY_EMAIL = config('PRIVACY_EMAIL', default='privacy@nzilaventures.com')

# Company Information (for email templates)
COMPANY_NAME = config('COMPANY_NAME', default='Nzila Export')
SUPPORT_PHONE = config('SUPPORT_PHONE', default='1-800-NZILA-EX')
PRIVACY_POLICY_URL = config('PRIVACY_POLICY_URL', default='https://nzilaexport.com/privacy')
MANAGE_PREFERENCES_URL = config('MANAGE_PREFERENCES_URL', default='https://nzilaexport.com/preferences')
DASHBOARD_URL = config('DASHBOARD_URL', default='https://nzilaexport.com/dashboard')
TRACKING_URL = config('TRACKING_URL', default='https://nzilaexport.com/track')

# Email Template Directory
TEMPLATES[0]['DIRS'].append(BASE_DIR / 'email_templates')


# Exchange Rate API Configuration
# Get free API key from: https://www.exchangerate-api.com/
EXCHANGE_RATE_API_KEY = config('EXCHANGE_RATE_API_KEY', default=None)

# Canadian Vehicle Data API Configuration
CARFAX_API_KEY = config('CARFAX_API_KEY', default=None)
AUTOCHECK_API_KEY = config('AUTOCHECK_API_KEY', default=None)
ICBC_API_KEY = config('ICBC_API_KEY', default=None)  # British Columbia
MTO_API_KEY = config('MTO_API_KEY', default=None)  # Ontario
SAAQ_API_KEY = config('SAAQ_API_KEY', default=None)  # Quebec

# Lloyd's Register Cargo Tracking Service (CTS) Configuration
# For world-class marine cargo certification and third-party verification
# Register at: https://www.lr.org/en/services/cargo-tracking/
LLOYD_REGISTER_API_KEY = config('LLOYD_REGISTER_API_KEY', default=None)
LLOYD_REGISTER_CLIENT_ID = config('LLOYD_REGISTER_CLIENT_ID', default=None)
LLOYD_REGISTER_API_URL = config('LLOYD_REGISTER_API_URL', 
                                default='https://api.lr.org/cargo-tracking/v1')

# ISO 28000 Security Management Configuration
ISO_28000_ENABLED = config('ISO_28000_ENABLED', default=True, cast=bool)
CTPAT_COMPLIANCE_ENABLED = config('CTPAT_COMPLIANCE_ENABLED', default=True, cast=bool)

# Django Debug Toolbar Configuration (development only)
INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]

# Sentry Configuration - Error Tracking & Performance Monitoring (APM)
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.redis import RedisIntegration
from sentry_sdk.integrations.logging import LoggingIntegration

SENTRY_DSN = config('SENTRY_DSN', default='')
SENTRY_ENVIRONMENT = config('SENTRY_ENVIRONMENT', default='development')

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(
                # Track SQL queries for performance monitoring
                transaction_style='url',
                middleware_spans=True,
                signals_spans=True,
                cache_spans=True,
            ),
            CeleryIntegration(
                # Track Celery task performance
                monitor_beat_tasks=True,
                propagate_traces=True,
            ),
            RedisIntegration(),
            LoggingIntegration(
                level=None,  # Capture all log levels
                event_level=None  # Don't create events from logs automatically
            ),
        ],
        # Performance monitoring - sample rate based on environment
        # Production: 10% (reduce overhead), Staging: 50%, Development: 100%
        traces_sample_rate=config('SENTRY_TRACES_SAMPLE_RATE', default=0.1, cast=float),
        
        # Profile 10% of transactions for detailed performance analysis
        profiles_sample_rate=config('SENTRY_PROFILES_SAMPLE_RATE', default=0.1, cast=float),
        
        # Send errors from this environment
        environment=SENTRY_ENVIRONMENT,
        
        # Release tracking (for correlating errors to deployments)
        release=config('APP_VERSION', default='1.0.0'),
        
        # Include request headers and IP for users (PII data)
        send_default_pii=config('SENTRY_SEND_PII', default=True, cast=bool),
        
        # Ignore common errors that don't need tracking
        ignore_errors=[
            KeyboardInterrupt,
            BrokenPipeError,
        ],
        
        # Before send callback for filtering/enriching events
        before_send=lambda event, hint: event if not DEBUG else None,  # Don't send in debug mode
        
        # Set max_breadcrumbs to track user actions leading to errors
        max_breadcrumbs=50,
        
        # Attach local variables to stack traces (helpful for debugging)
        attach_stacktrace=True,
        
        # Enable automatic performance instrumentation
        auto_enabling_integrations=True,
        
        # Database query performance threshold (alert if query >100ms)
        _experiments={
            "record_sql_params": True,  # Record SQL query parameters
        },
    )
    
    # Configure slow query detection (queries slower than 100ms)
    import logging
    logger = logging.getLogger('django.db.backends')
    logger.setLevel(logging.DEBUG if DEBUG else logging.WARNING)
