"""
Django settings for nzila_export project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default='False', cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Frontend URL for email links
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:5174',
    'http://localhost:5175',
    'http://localhost:5176',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:5174',
    'http://127.0.0.1:5175',
    'http://127.0.0.1:5176',
    'http://localhost:3000',
    'http://localhost:3001',
]
CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    'daphne',  # Django Channels ASGI server - must be before django.contrib.staticfiles
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',  # Django Channels for WebSockets
    'corsheaders',
    'rest_framework',
    'django_filters',
    # Project apps
    'nzila_export',
    'accounts',
    'vehicles',
    'deals',
    'shipments',
    'commissions',
    'analytics',
    'notifications',
    'payments',
    'audit',
    'favorites',
    'email_templates',
    'saved_searches',
    'price_alerts',
    'recommendations',
    'vehicle_history',
    'analytics_dashboard',
    'chat',
    'reviews',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Audit middleware
    'audit.middleware.AuditMiddleware',
    'audit.middleware.SecurityAuditMiddleware',
]

ROOT_URLCONF = 'nzila_export.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'nzila_export.wsgi.application'

# ASGI Application (Django Channels for WebSockets)
ASGI_APPLICATION = 'nzila_export.asgi_channels.application'

# Django Channels Configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(os.environ.get('REDIS_HOST', '127.0.0.1'), 6379)],
            "capacity": 1500,  # Max messages in channel before blocking
            "expiry": 10,  # Message expiry in seconds
        },
    },
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # Connection pooling settings
        'CONN_MAX_AGE': 600,  # Keep connections alive for 10 minutes
        'CONN_HEALTH_CHECKS': True,  # Check connection health before using
        'OPTIONS': {
            'timeout': 20,  # Database timeout in seconds
        },
    }
}

# PostgreSQL SSL Configuration (Production)
# Override DATABASES in production settings to include:
# 'OPTIONS': {
#     'sslmode': 'require',
#     'sslrootcert': '/path/to/root.crt',
#     'sslcert': '/path/to/client.crt',
#     'sslkey': '/path/to/client.key',
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('fr', 'Français'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'America/Toronto'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.JWTCookieAuthentication',  # Custom cookie-based JWT
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # API Rate Limiting - Production Security Settings
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # Anonymous users: 0.03 req/sec (realistic browsing)
        'user': '1000/hour',  # Authenticated users: 0.28 req/sec (normal API usage)
        'payment': '10/hour',  # Payment endpoints: Max 10 payment attempts/hour
        'login': '5/minute',  # Login attempts: 5/min to prevent credential stuffing
        'registration': '3/hour',  # User registration: Prevent bot signups
        'password_reset': '3/hour',  # Password reset: Prevent email bombing
        'vehicle_history': '50/hour',  # CarFax/AutoCheck API calls (reduced costs)
        'transport_canada': '500/hour',  # Transport Canada public data
        'provincial_registry': '50/hour',  # Provincial registry APIs
    },
}

# Stripe Payment Configuration
# Stripe Payment Configuration
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

# Twilio SMS Configuration (for 2FA)
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default='')

# Multi-Currency Configuration
DEFAULT_CURRENCY = config('DEFAULT_CURRENCY', default='USD')
SUPPORTED_CURRENCIES = config('SUPPORTED_CURRENCIES', cast=Csv(), 
                             default='USD,EUR,GBP,ZAR,NGN,KES,GHS,EGP')

# African Payment Gateways (Optional)
FLUTTERWAVE_SECRET_KEY = config('FLUTTERWAVE_SECRET_KEY', default='')
FLUTTERWAVE_PUBLIC_KEY = config('FLUTTERWAVE_PUBLIC_KEY', default='')
CARFAX_API_URL = config('CARFAX_API_URL', default='https://api.carfax.com/v1')
CARFAX_CACHE_TTL = config('CARFAX_CACHE_TTL', default=604800, cast=int)  # 7 days
AUTOCHECK_API_KEY = config('AUTOCHECK_API_KEY', default=None)
ICBC_API_KEY = config('ICBC_API_KEY', default=None)  # British Columbia
MTO_API_KEY = config('MTO_API_KEY', default=None)  # Ontario
SAAQ_API_KEY = config('SAAQ_API_KEY', default=None)  # Quebec

# WhatsApp Business API Configuration
WHATSAPP_API_TOKEN = config('WHATSAPP_API_TOKEN', default=None)
WHATSAPP_PHONE_NUMBER_ID = config('WHATSAPP_PHONE_NUMBER_ID', default=None)
WHATSAPP_VERIFY_TOKEN = config('WHATSAPP_VERIFY_TOKEN', default=None)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@nzilaventures.com')
ADMIN_EMAIL = config('ADMIN_EMAIL', default='info@nzilaventures.com')

# Exchange Rate API Configuration
# Get free API key from: https://www.exchangerate-api.com/
EXCHANGE_RATE_API_KEY = config('EXCHANGE_RATE_API_KEY', default=None)

# Canadian Vehicle Data API Configuration
CARFAX_API_KEY = config('CARFAX_API_KEY', default=None)
AUTOCHECK_API_KEY = config('AUTOCHECK_API_KEY', default=None)
ICBC_API_KEY = config('ICBC_API_KEY', default=None)  # British Columbia
MTO_API_KEY = config('MTO_API_KEY', default=None)  # Ontario
SAAQ_API_KEY = config('SAAQ_API_KEY', default=None)  # Quebec

# Lloyd's Register Cargo Tracking Service (CTS) Configuration
# For world-class marine cargo certification and third-party verification
# Register at: https://www.lr.org/en/services/cargo-tracking/
LLOYD_REGISTER_API_KEY = config('LLOYD_REGISTER_API_KEY', default=None)
LLOYD_REGISTER_CLIENT_ID = config('LLOYD_REGISTER_CLIENT_ID', default=None)
LLOYD_REGISTER_API_URL = config('LLOYD_REGISTER_API_URL', 
                                default='https://api.lr.org/cargo-tracking/v1')

# ISO 28000 Security Management Configuration
ISO_28000_ENABLED = config('ISO_28000_ENABLED', default=True, cast=bool)
CTPAT_COMPLIANCE_ENABLED = config('CTPAT_COMPLIANCE_ENABLED', default=True, cast=bool)

# Sentry Configuration - Error Tracking & Performance Monitoring
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration

SENTRY_DSN = config('SENTRY_DSN', default='')
SENTRY_ENVIRONMENT = config('SENTRY_ENVIRONMENT', default='development')

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
        ],
        # Performance monitoring - sample 10% of transactions
        traces_sample_rate=0.1,
        # Profile 10% of transactions
        profiles_sample_rate=0.1,
        # Send errors from this environment
        environment=SENTRY_ENVIRONMENT,
        # Release tracking
        release=config('APP_VERSION', default='1.0.0'),
        # Include request headers and IP for users (PII data)
        send_default_pii=True,
    )
