# Generated by Django 4.2.27 on 2025-12-16 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("suspicious_login", "Suspicious Login"),
                            ("multiple_failed_logins", "Multiple Failed Logins"),
                            ("password_reset_request", "Password Reset Request"),
                            ("password_reset_complete", "Password Reset Complete"),
                            ("account_locked", "Account Locked"),
                            ("account_unlocked", "Account Unlocked"),
                            ("2fa_bypass_attempt", "2FA Bypass Attempt"),
                            ("permission_denied", "Permission Denied"),
                            ("api_rate_limit_exceeded", "API Rate Limit Exceeded"),
                            ("sql_injection_attempt", "SQL Injection Attempt"),
                            ("xss_attempt", "XSS Attempt"),
                            ("csrf_failure", "CSRF Failure"),
                            ("unusual_activity", "Unusual Activity"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("blocked", models.BooleanField(default=False)),
                ("action_taken", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Event",
                "verbose_name_plural": "Security Events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "risk_level"],
                        name="audit_secur_timesta_707d4f_idx",
                    ),
                    models.Index(
                        fields=["resolved", "-timestamp"],
                        name="audit_secur_resolve_c126c5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("failure_reason", models.CharField(blank=True, max_length=200)),
                ("failed_attempts", models.IntegerField(default=0)),
                ("session_key", models.CharField(blank=True, max_length=100)),
                (
                    "login_timestamp",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("logout_timestamp", models.DateTimeField(blank=True, null=True)),
                ("session_duration", models.DurationField(blank=True, null=True)),
                ("two_factor_used", models.BooleanField(default=False)),
                ("two_factor_method", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Login History",
                "verbose_name_plural": "Login Histories",
                "ordering": ["-login_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-login_timestamp"],
                        name="audit_login_user_id_e1b96b_idx",
                    ),
                    models.Index(
                        fields=["status", "-login_timestamp"],
                        name="audit_login_status_9f9618_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                ("object_repr", models.CharField(max_length=200)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("reason", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Change Log",
                "verbose_name_plural": "Data Change Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "object_id", "-timestamp"],
                        name="audit_datac_model_n_caf99d_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_datac_user_id_16745d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login Failed"),
                            ("password_change", "Password Change"),
                            ("2fa_enabled", "2FA Enabled"),
                            ("2fa_disabled", "2FA Disabled"),
                            ("payment_created", "Payment Created"),
                            ("payment_succeeded", "Payment Succeeded"),
                            ("payment_failed", "Payment Failed"),
                            ("payment_refunded", "Payment Refunded"),
                            ("invoice_created", "Invoice Created"),
                            ("invoice_sent", "Invoice Sent"),
                            ("invoice_paid", "Invoice Paid"),
                            ("deal_created", "Deal Created"),
                            ("deal_updated", "Deal Updated"),
                            ("deal_status_changed", "Deal Status Changed"),
                            ("shipment_created", "Shipment Created"),
                            ("shipment_updated", "Shipment Updated"),
                            ("document_uploaded", "Document Uploaded"),
                            ("document_deleted", "Document Deleted"),
                            ("commission_calculated", "Commission Calculated"),
                            ("commission_paid", "Commission Paid"),
                            ("settings_changed", "Settings Changed"),
                            ("export", "Data Export"),
                            ("import", "Data Import"),
                            ("api_call", "API Call"),
                            ("webhook_received", "Webhook Received"),
                            ("email_sent", "Email Sent"),
                            ("sms_sent", "SMS Sent"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "action"],
                        name="audit_audit_timesta_c7b922_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_audit_user_id_ea8c9f_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_audit_content_4c2ead_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="APIAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(db_index=True, max_length=10)),
                ("path", models.CharField(db_index=True, max_length=500)),
                ("query_params", models.TextField(blank=True)),
                ("status_code", models.IntegerField(db_index=True)),
                ("response_time_ms", models.IntegerField()),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("request_body_size", models.IntegerField(default=0)),
                ("response_body_size", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Access Log",
                "verbose_name_plural": "API Access Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "status_code"],
                        name="audit_apiac_timesta_abaa75_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_apiac_user_id_3fc1b5_idx",
                    ),
                    models.Index(
                        fields=["path", "-timestamp"],
                        name="audit_apiac_path_761b0b_idx",
                    ),
                ],
            },
        ),
    ]
