# Generated by Django 6.0 on 2025-12-15 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Make')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('condition', models.CharField(choices=[('new', 'New'), ('used_excellent', 'Used - Excellent'), ('used_good', 'Used - Good'), ('used_fair', 'Used - Fair')], default='used_good', max_length=20, verbose_name='Condition')),
                ('mileage', models.IntegerField(verbose_name='Mileage (km)')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('fuel_type', models.CharField(blank=True, max_length=50, verbose_name='Fuel Type')),
                ('transmission', models.CharField(blank=True, max_length=50, verbose_name='Transmission')),
                ('price_cad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (CAD)')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='available', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.CharField(max_length=255, verbose_name='Location in Canada')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Main Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(limit_choices_to={'role': 'dealer'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Dealer')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Image',
                'verbose_name_plural': 'Vehicle Images',
            },
        ),
    ]
