# Generated by Django 4.2.27 on 2025-12-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicleimage",
            options={
                "ordering": ["order", "-uploaded_at"],
                "verbose_name": "Vehicle Image",
                "verbose_name_plural": "Vehicle Images",
            },
        ),
        migrations.AddField(
            model_name="vehicleimage",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="Is Primary Image"),
        ),
        migrations.AddField(
            model_name="vehicleimage",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Display Order"),
        ),
    ]
