# Generated by Django 4.2.27 on 2025-12-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicleimage_options_vehicleimage_is_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='drivetrain',
            field=models.CharField(blank=True, choices=[('fwd', 'Front-Wheel Drive (FWD)'), ('rwd', 'Rear-Wheel Drive (RWD)'), ('awd', 'All-Wheel Drive (AWD)'), ('4wd', 'Four-Wheel Drive (4WD)')], max_length=50, verbose_name='Drivetrain'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(blank=True, choices=[('4-cylinder', '4 Cylinder'), ('6-cylinder', '6 Cylinder'), ('8-cylinder', '8 Cylinder'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('diesel', 'Diesel')], max_length=50, verbose_name='Engine Type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('plug-in-hybrid', 'Plug-in Hybrid')], max_length=50, verbose_name='Fuel Type'),
        ),
    ]
