# Generated by Django 4.2.27 on 2025-12-16 19:24

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0003_vehicle_drivetrain_vehicle_engine_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_amount_cad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Offer Amount (CAD)')),
                ('message', models.TextField(blank=True, verbose_name='Message to Dealer')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Countered'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('counter_amount_cad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Counter Offer Amount (CAD)')),
                ('counter_message', models.TextField(blank=True, verbose_name='Counter Offer Message')),
                ('dealer_notes', models.TextField(blank=True, verbose_name='Dealer Notes')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded At')),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_offers', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle', 'status'], name='vehicles_of_vehicle_7f96b4_idx'), models.Index(fields=['buyer', 'status'], name='vehicles_of_buyer_i_779a77_idx'), models.Index(fields=['-created_at'], name='vehicles_of_created_37e2a8_idx')],
            },
        ),
    ]
