# Generated by Django 4.2.27 on 2025-12-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'ordering': ['order', '-uploaded_at'], 'verbose_name': 'Vehicle Media', 'verbose_name_plural': 'Vehicle Media'},
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Video Duration (seconds)'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10, verbose_name='Media Type'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/thumbnails/%Y/%m/%d/', verbose_name='Video Thumbnail'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/videos/%Y/%m/%d/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/images/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
