# Generated by Django 4.2.27 on 2025-12-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0005_alter_vehicleimage_options_and_more"),
    ]

    operations = [
        # Add index on status field (heavily filtered in get_queryset)
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='vehicles_status_idx'),
        ),
        # Add index on make field (used in filterset_fields and search)
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make'], name='vehicles_make_idx'),
        ),
        # Add index on year field (used in filterset_fields and ordering)
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['year'], name='vehicles_year_idx'),
        ),
        # Add index on created_at for ordering
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['-created_at'], name='vehicles_created_idx'),
        ),
        # Add composite index for most common filter combination
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status', 'make'], name='vehicles_status_make_idx'),
        ),
        # Add index on dealer FK for dealer-specific queries
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['dealer'], name='vehicles_dealer_idx'),
        ),
        # Add index on price for sorting and range queries
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['price_cad'], name='vehicles_price_idx'),
        ),
        # Offer model indexes
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status'], name='offers_status_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['-created_at'], name='offers_created_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['vehicle'], name='offers_vehicle_idx'),
        ),
    ]
