# Generated by Django 4.2.27 on 2025-12-20 18:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vehicles", "0006_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        help_text="Phone number for day-of coordination",
                        max_length=20,
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Contact Email"),
                ),
                (
                    "number_of_people",
                    models.IntegerField(
                        default=1,
                        help_text="How many people will attend the inspection",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Number of People",
                    ),
                ),
                (
                    "buyer_notes",
                    models.TextField(
                        blank=True,
                        help_text="Special requests or questions from buyer",
                        verbose_name="Buyer Notes",
                    ),
                ),
                (
                    "dealer_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for dealer staff",
                        verbose_name="Dealer Notes",
                    ),
                ),
                (
                    "inspection_feedback",
                    models.TextField(
                        blank=True,
                        help_text="Buyer feedback after inspection",
                        verbose_name="Inspection Feedback",
                    ),
                ),
                (
                    "vehicle_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="1-5 stars: How did vehicle match expectations?",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Vehicle Rating",
                    ),
                ),
                (
                    "dealer_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="1-5 stars: How was the inspection experience?",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Dealer Rating",
                    ),
                ),
                (
                    "interested_in_purchase",
                    models.BooleanField(
                        default=False,
                        help_text="Buyer wants to proceed with purchase after inspection",
                        verbose_name="Interested in Purchase",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmed At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelled At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection Appointment",
                "verbose_name_plural": "Inspection Appointments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleInspectionSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Inspection Date")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Available"),
                ),
                (
                    "max_attendees",
                    models.IntegerField(
                        default=1,
                        help_text="How many buyers can inspect at this time",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Maximum Attendees",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Special instructions for this time slot",
                        verbose_name="Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vehicle Inspection Slot",
                "verbose_name_plural": "Vehicle Inspection Slots",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.RemoveIndex(
            model_name="offer",
            name="offers_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="offer",
            name="offers_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="offer",
            name="offers_vehicle_idx",
        ),
        migrations.RemoveIndex(
            model_name="vehicle",
            name="vehicles_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="vehicle",
            name="vehicles_make_idx",
        ),
        migrations.RemoveIndex(
            model_name="vehicle",
            name="vehicles_year_idx",
        ),
        migrations.RemoveIndex(
            model_name="vehicle",
            name="vehicles_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="vehicle",
            name="vehicles_status_make_idx",
        ),
        migrations.RemoveIndex(
            model_name="vehicle",
            name="vehicles_dealer_idx",
        ),
        migrations.RemoveIndex(
            model_name="vehicle",
            name="vehicles_price_idx",
        ),
        migrations.AddField(
            model_name="vehicleinspectionslot",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspection_slots",
                to="vehicles.vehicle",
                verbose_name="Vehicle",
            ),
        ),
        migrations.AddField(
            model_name="inspectionappointment",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspection_appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Buyer",
            ),
        ),
        migrations.AddField(
            model_name="inspectionappointment",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="vehicles.vehicleinspectionslot",
                verbose_name="Inspection Slot",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleinspectionslot",
            index=models.Index(
                fields=["vehicle", "date", "is_available"],
                name="vehicles_ve_vehicle_bfbc83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleinspectionslot",
            index=models.Index(
                fields=["date", "start_time"], name="vehicles_ve_date_de8107_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vehicleinspectionslot",
            unique_together={("vehicle", "date", "start_time")},
        ),
        migrations.AddIndex(
            model_name="inspectionappointment",
            index=models.Index(
                fields=["buyer", "status"], name="vehicles_in_buyer_i_061d6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionappointment",
            index=models.Index(
                fields=["slot", "status"], name="vehicles_in_slot_id_b7b7d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionappointment",
            index=models.Index(
                fields=["-created_at"], name="vehicles_in_created_1256cd_idx"
            ),
        ),
    ]
