# Generated by Django 4.2.27 on 2025-12-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0007_inspectionappointment_vehicleinspectionslot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude coordinate for proximity search",
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude coordinate for proximity search",
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
    ]
