# Generated by Django 4.2.27 on 2025-12-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0008_add_geographic_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="lien_checked",
            field=models.BooleanField(
                default=False,
                help_text="Whether PPSA lien search has been performed",
                verbose_name="Lien Checked",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="lien_status",
            field=models.CharField(
                blank=True,
                help_text="CLEAR, LIEN_FOUND, or empty if not checked",
                max_length=20,
                verbose_name="Lien Status",
            ),
        ),
    ]
