# Generated by Django 4.2.27 on 2025-12-20 19:44

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vehicles", "0009_vehicle_lien_checked_vehicle_lien_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThirdPartyInspector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the inspector or primary contact",
                        max_length=200,
                        verbose_name="Inspector Name",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        help_text="Business or company name",
                        max_length=200,
                        verbose_name="Company Name",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("ON", "Ontario"),
                            ("QC", "Quebec"),
                            ("BC", "British Columbia"),
                            ("AB", "Alberta"),
                            ("MB", "Manitoba"),
                            ("SK", "Saskatchewan"),
                            ("NS", "Nova Scotia"),
                            ("NB", "New Brunswick"),
                            ("NL", "Newfoundland and Labrador"),
                            ("PE", "Prince Edward Island"),
                            ("YT", "Yukon"),
                            ("NT", "Northwest Territories"),
                            ("NU", "Nunavut"),
                        ],
                        max_length=2,
                        verbose_name="Province",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Street Address"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="Postal Code"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Geographic latitude for proximity search",
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Geographic longitude for proximity search",
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone Number")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Inspector or company website",
                        verbose_name="Website",
                    ),
                ),
                (
                    "certifications",
                    models.CharField(
                        choices=[
                            ("ase", "ASE Certified"),
                            ("ari", "ARI Certified"),
                            ("red_seal", "Red Seal Technician"),
                            ("provincially_licensed", "Provincially Licensed"),
                            ("caa_approved", "CAA Approved"),
                            ("manufacturer_certified", "Manufacturer Certified"),
                            ("independent", "Independent Inspector"),
                        ],
                        default="independent",
                        help_text="Main certification or accreditation",
                        max_length=50,
                        verbose_name="Primary Certification",
                    ),
                ),
                (
                    "additional_certifications",
                    models.TextField(
                        blank=True,
                        help_text="Other certifications, comma-separated",
                        verbose_name="Additional Certifications",
                    ),
                ),
                (
                    "years_experience",
                    models.IntegerField(
                        default=0,
                        help_text="Years in vehicle inspection business",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Years of Experience",
                    ),
                ),
                (
                    "specializations",
                    models.TextField(
                        blank=True,
                        help_text='e.g., "Luxury vehicles, Electric vehicles, Classic cars"',
                        verbose_name="Specializations",
                    ),
                ),
                (
                    "mobile_service",
                    models.BooleanField(
                        default=False,
                        help_text="Inspector will travel to vehicle location",
                        verbose_name="Mobile Service Available",
                    ),
                ),
                (
                    "service_radius_km",
                    models.IntegerField(
                        default=50,
                        help_text="Maximum distance for mobile inspections",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Service Radius (km)",
                    ),
                ),
                (
                    "inspection_fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base fee for standard pre-purchase inspection",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Standard Inspection Fee (CAD)",
                    ),
                ),
                (
                    "mobile_fee_extra",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Additional charge for mobile inspections",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Mobile Service Extra Fee (CAD)",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Calculated from reviews (0.00 - 5.00)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("5.00")),
                        ],
                        verbose_name="Average Rating",
                    ),
                ),
                (
                    "total_inspections",
                    models.IntegerField(
                        default=0,
                        help_text="Number of inspections completed through platform",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total Inspections",
                    ),
                ),
                (
                    "total_reviews",
                    models.IntegerField(
                        default=0,
                        help_text="Number of reviews received",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total Reviews",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inspector is currently accepting bookings",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Inspector credentials verified by platform",
                        verbose_name="Verified",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Third-Party Inspector",
                "verbose_name_plural": "Third-Party Inspectors",
                "ordering": ["-rating", "-total_inspections", "company"],
                "indexes": [
                    models.Index(
                        fields=["province", "city"],
                        name="inspections_provinc_ed503d_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_verified"],
                        name="inspections_is_acti_952592_idx",
                    ),
                    models.Index(
                        fields=["-rating", "-total_inspections"],
                        name="inspections_rating_108c32_idx",
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="inspections_latitud_b1da4b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InspectionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("pre_purchase", "Pre-Purchase Inspection"),
                            ("comprehensive", "Comprehensive Inspection"),
                            ("mechanical", "Mechanical Only"),
                            ("body_frame", "Body & Frame Only"),
                            ("electrical", "Electrical Systems"),
                            ("safety", "Safety Inspection"),
                            ("emissions", "Emissions Test"),
                        ],
                        default="pre_purchase",
                        max_length=30,
                        verbose_name="Report Type",
                    ),
                ),
                (
                    "inspection_date",
                    models.DateField(
                        help_text="Date inspection was performed",
                        verbose_name="Inspection Date",
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        help_text="Uploaded inspection report (PDF, DOC, or images)",
                        upload_to="inspection_reports/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                ]
                            )
                        ],
                        verbose_name="Report File",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "overall_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent - No issues found"),
                            ("good", "Good - Minor cosmetic issues only"),
                            ("fair", "Fair - Some repairs recommended"),
                            ("poor", "Poor - Major repairs required"),
                            (
                                "not_recommended",
                                "Not Recommended - Serious safety concerns",
                            ),
                        ],
                        max_length=30,
                        verbose_name="Overall Condition Assessment",
                    ),
                ),
                (
                    "issues_found",
                    models.TextField(
                        blank=True,
                        help_text="List of issues discovered during inspection",
                        verbose_name="Issues Found",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="Recommended repairs or actions",
                        verbose_name="Inspector Recommendations",
                    ),
                ),
                (
                    "estimated_repair_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Inspector's estimate for recommended repairs",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Estimated Repair Cost (CAD)",
                    ),
                ),
                (
                    "engine_score",
                    models.IntegerField(
                        blank=True,
                        help_text="0-10 rating for engine condition",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Engine Score",
                    ),
                ),
                (
                    "transmission_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Transmission Score",
                    ),
                ),
                (
                    "suspension_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Suspension Score",
                    ),
                ),
                (
                    "brakes_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Brakes Score",
                    ),
                ),
                (
                    "body_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Body Score",
                    ),
                ),
                (
                    "interior_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Interior Score",
                    ),
                ),
                (
                    "inspection_fee_paid",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid for this inspection",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Inspection Fee Paid (CAD)",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Any additional information or special circumstances",
                        verbose_name="Additional Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        help_text="Buyer who requested the inspection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_inspections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requesting Buyer",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="inspections.thirdpartyinspector",
                        verbose_name="Inspector",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_reports",
                        to="vehicles.vehicle",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection Report",
                "verbose_name_plural": "Inspection Reports",
                "ordering": ["-inspection_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="1-5 stars rating",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "review_text",
                    models.TextField(
                        help_text="Detailed review of the inspection experience",
                        verbose_name="Review",
                    ),
                ),
                (
                    "professionalism_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Inspector's professional conduct",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Professionalism",
                    ),
                ),
                (
                    "thoroughness_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="How thorough was the inspection",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Thoroughness",
                    ),
                ),
                (
                    "communication_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Quality of communication and explanations",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Communication",
                    ),
                ),
                (
                    "value_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Was the service worth the cost",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Value for Money",
                    ),
                ),
                (
                    "helpful_votes",
                    models.IntegerField(
                        default=0,
                        help_text="Number of users who found this review helpful",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Helpful Votes",
                    ),
                ),
                (
                    "is_verified_purchase",
                    models.BooleanField(
                        default=True,
                        help_text="Review is from actual inspection through platform",
                        verbose_name="Verified Inspection",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Review is visible to other users",
                        verbose_name="Published",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspector_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewer",
                    ),
                ),
                (
                    "inspection_report",
                    models.OneToOneField(
                        help_text="Inspection this review is based on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="inspections.inspectionreport",
                        verbose_name="Related Inspection",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="inspections.thirdpartyinspector",
                        verbose_name="Inspector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspector Review",
                "verbose_name_plural": "Inspector Reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["inspector", "-created_at"],
                        name="inspections_inspect_c32451_idx",
                    ),
                    models.Index(
                        fields=["-rating", "-helpful_votes"],
                        name="inspections_rating_cc0689_idx",
                    ),
                ],
                "unique_together": {("buyer", "inspection_report")},
            },
        ),
        migrations.AddIndex(
            model_name="inspectionreport",
            index=models.Index(
                fields=["vehicle", "status"], name="inspections_vehicle_d65668_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionreport",
            index=models.Index(
                fields=["inspector", "status"], name="inspections_inspect_989e4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionreport",
            index=models.Index(
                fields=["buyer", "-created_at"], name="inspections_buyer_i_beb56f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionreport",
            index=models.Index(
                fields=["-inspection_date"], name="inspections_inspect_5956f3_idx"
            ),
        ),
    ]
