# Generated by Django 6.0 on 2025-12-15 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('broker', 'Broker Commission'), ('dealer', 'Dealer Commission')], max_length=20, verbose_name='Commission Type')),
                ('amount_cad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (CAD)')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Commission percentage', max_digits=5, verbose_name='Percentage')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='deals.deal', verbose_name='Deal')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
