# Generated by Django 4.2.27 on 2025-12-17 02:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount (USD)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.0'), help_text='CAD to USD exchange rate at time of deal', max_digits=10, verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='commission',
            name='payment_currency',
            field=models.CharField(choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar')], default='CAD', max_length=3, verbose_name='Payment Currency'),
        ),
        migrations.CreateModel(
            name='DealerTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_tier', models.CharField(choices=[('standard', 'Standard'), ('preferred', 'Preferred'), ('elite', 'Elite'), ('premier', 'Premier')], default='standard', max_length=20, verbose_name='Current Tier')),
                ('province', models.CharField(blank=True, choices=[('ON', 'Ontario'), ('QC', 'Quebec'), ('BC', 'British Columbia'), ('AB', 'Alberta'), ('SK', 'Saskatchewan'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NS', 'Nova Scotia'), ('PE', 'Prince Edward Island'), ('NL', 'Newfoundland and Labrador'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut')], max_length=2, verbose_name='Province')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('is_rural', models.BooleanField(default=False, verbose_name='Rural Dealer')),
                ('is_first_nations', models.BooleanField(default=False, verbose_name='First Nations Partnership')),
                ('omvic_certified', models.BooleanField(default=False, help_text='Ontario Motor Vehicle Industry Council', verbose_name='OMVIC Certified')),
                ('amvic_certified', models.BooleanField(default=False, help_text='Alberta Motor Vehicle Industry Council', verbose_name='AMVIC Certified')),
                ('certification_bonus_paid', models.BooleanField(default=False)),
                ('deals_this_quarter', models.IntegerField(default=0, verbose_name='Deals This Quarter')),
                ('deals_last_quarter', models.IntegerField(default=0, verbose_name='Deals Last Quarter')),
                ('total_deals', models.IntegerField(default=0, verbose_name='Total Deals')),
                ('average_deal_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Average Deal Value')),
                ('total_commissions_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Commissions Earned')),
                ('welcome_bonus_paid', models.BooleanField(default=False)),
                ('first_deal_bonus_paid', models.BooleanField(default=False)),
                ('fast_start_bonus_paid', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_tier', to=settings.AUTH_USER_MODEL, verbose_name='Dealer')),
            ],
            options={
                'verbose_name': 'Dealer Tier',
                'verbose_name_plural': 'Dealer Tiers',
                'ordering': ['-deals_this_quarter'],
            },
        ),
        migrations.CreateModel(
            name='BrokerTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_tier', models.CharField(choices=[('starter', 'Starter'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='starter', max_length=20, verbose_name='Current Tier')),
                ('deals_this_month', models.IntegerField(default=0, verbose_name='Deals This Month')),
                ('volume_this_month', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Volume This Month (CAD)')),
                ('total_deals', models.IntegerField(default=0, verbose_name='Total Deals')),
                ('total_commissions_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Commissions Earned (CAD)')),
                ('average_deal_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Average Deal Value')),
                ('streak_days', models.IntegerField(default=0, help_text='Consecutive days with activity')),
                ('highest_month', models.IntegerField(default=0, help_text='Most deals in a single month')),
                ('last_deal_date', models.DateField(blank=True, null=True, verbose_name='Last Deal Date')),
                ('achievement_boost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Permanent % boost from achievements', max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_tier', to=settings.AUTH_USER_MODEL, verbose_name='Broker')),
            ],
            options={
                'verbose_name': 'Broker Tier',
                'verbose_name_plural': 'Broker Tiers',
                'ordering': ['-deals_this_month'],
            },
        ),
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.CharField(choices=[('welcome', 'Welcome Bonus'), ('first_deal', 'First Deal Bonus'), ('fast_start', 'Fast Start Bonus (5 deals in 30 days)'), ('certification', 'Certification Bonus (OMVIC/AMVIC)'), ('referral', 'Dealer Referral Bonus'), ('achievement', 'Achievement Bonus'), ('milestone', 'Milestone Bonus')], max_length=30, verbose_name='Bonus Type')),
                ('amount_cad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (CAD)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Bonus Transaction',
                'verbose_name_plural': 'Bonus Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
