# Generated by Django 4.2.27 on 2025-12-17 02:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_commission_amount_usd_commission_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokertier',
            name='buyer_conversion_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% of introductions that result in deals', max_digits=5, verbose_name='Buyer Conversion Rate %'),
        ),
        migrations.AddField(
            model_name='brokertier',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='brokertier',
            name='country',
            field=models.CharField(choices=[('CI', "Côte d'Ivoire"), ('SN', 'Senegal'), ('GH', 'Ghana'), ('NG', 'Nigeria'), ('BJ', 'Benin'), ('TG', 'Togo'), ('BF', 'Burkina Faso'), ('ML', 'Mali'), ('CM', 'Cameroon'), ('CD', 'Democratic Republic of Congo'), ('KE', 'Kenya'), ('ZA', 'South Africa'), ('MA', 'Morocco'), ('TN', 'Tunisia'), ('EG', 'Egypt'), ('OTHER', 'Other')], default='CI', help_text="Most brokers are based in Côte d'Ivoire", max_length=10, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='brokertier',
            name='qualified_buyers_network',
            field=models.IntegerField(default=0, help_text='Number of verified buyers this broker has connected', verbose_name='Qualified Buyers in Network'),
        ),
        migrations.AddField(
            model_name='brokertier',
            name='timezone',
            field=models.CharField(choices=[('Africa/Abidjan', 'West Africa (GMT)'), ('Africa/Lagos', 'West Africa Central (WAT)'), ('Africa/Nairobi', 'East Africa (EAT)'), ('Africa/Cairo', 'Egypt (EET)'), ('Africa/Johannesburg', 'South Africa (SAST)'), ('Africa/Casablanca', 'Morocco (WET)'), ('America/Toronto', 'Canada (EST/EDT)')], default='Africa/Abidjan', help_text='Used for activity tracking and leaderboard rankings', max_length=50, verbose_name='Timezone'),
        ),
    ]
